[package]
name = "kindle-weather-rs"
version = "0.1.0"
authors = ["Gris Ge <cnfourt@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "*"
clap = "*"
dirs = "*"
toml = "*"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
strfmt = "*"
chrono = "*"
chrono-tz = "*"
